---
AWSTemplateFormatVersion: '2010-09-09'
Description: Join Windows instance to AWS-Active Directory or Microsoft AD (no powershell).
  Create SSM document, IAM Role, SSM doc and EC2 Instance. Attaches EC2 instance to
  AD. Will need to use Domain Logins to RDP in.
Parameters:
  AMI:
    Type: String
    Description: Windows 2016 AMI available in your region
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: KeyPair for EC2 Instance
  SecurityGroup:
    Description: Security Grouproup for EC2.
    Type: List<AWS::EC2::SecurityGroup::Id>
#  myEC2SSMRole:
#    Description: Enter role
#    Type: AWS::IAM::Role
#    Default: 'EC2DomainJoin'     
  PublicSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet to place instance in
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: VPC to place instance in
  VolumeSize:
    Description: Enter volume size  
    Type: String
    Default: 8  
  InstanceType:
    Type: String
    Default: t2.small
    AllowedValues:
    - t1.micro
    - t2.micro
    - t2.small
    - t2.medium
    - m1.small
    - m1.medium
    - m1.large
    - m1.xlarge
    - m2.xlarge
    - m2.2xlarge
    - m2.4xlarge
    - m3.medium
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - m5.large
    - m5.xlarge
    - m5.2xlarge
    - m5.4xlarge
    - c1.medium
    - c1.xlarge
    - c3.large
    - c3.xlarge
    - c3.2xlarge
    - c3.4xlarge
    - c3.8xlarge
    - c4.large
    - c4.xlarge
    - c4.2xlarge
    - c4.4xlarge
    - c4.8xlarge
    - g2.2xlarge
    - r3.large
    - r3.xlarge
    - r3.2xlarge
    - r3.4xlarge
    - r3.8xlarge
    - i2.xlarge
    - i2.2xlarge
    - i2.4xlarge
    - i2.8xlarge
    - d2.xlarge
    - d2.2xlarge
    - d2.4xlarge
    - d2.8xlarge
    - hi1.4xlarge
    - hs1.8xlarge
    - cr1.8xlarge
    - cc2.8xlarge
    - cg1.4xlarge
    ConstraintDescription: Must be a valid EC2 instance type.
  ADDirectoryId:
    Type: String
    Description: Active DirectoryId. Eg. d-12345679a
  ADDirectoryName:
    Type: String
    Description: Active Directory Name. Eg. my.ad.com
  ADDnsIpAddresses1:
    Type: String
    Description: Active Directory DNS 1. Eg. 10.0.0.142
  ADDnsIpAddresses2:
    Type: String
    Description: Active Directory DNS 2. Eg. 10.0.0.143
Resources:
  myssmdocument:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: '1.2'
        description: Join instances to an AWS Directory Service domain.
        parameters:
          directoryId:
            type: String
            description: "(Required) The ID of the AWS Directory Service directory."
          directoryName:
            type: String
            description: "(Required) The name of the directory; for example, test.example.com"
          dnsIpAddresses:
            type: StringList
            default: []
            description: "(Optional) The IP addresses of the DNS servers in the directory.
              Required when DHCP is not configured. Learn more at http://docs.aws.amazon.com/directoryservice/latest/simple-ad/join_get_dns_addresses.html"
            allowedPattern: "((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"
        runtimeConfig:
          aws:domainJoin:
            properties:
              directoryId: "{{ directoryId }}"
              directoryName: "{{ directoryName }}"
              dnsIpAddresses: "{{ dnsIpAddresses }}"
  myEC2InstanceSSM:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile:
        Ref: myInstanceProfile
      Tags:
      - Key: Name
        Value: !Sub "${AWS::StackName}"   
      SecurityGroupIds:
        Ref: SecurityGroup  
      SsmAssociations:
      - DocumentName:
          Ref: myssmdocument
        AssociationParameters:
        - Key: directoryId
          Value:
          - Ref: ADDirectoryId
        - Key: directoryName
          Value:
          - Ref: ADDirectoryName
        - Key: dnsIpAddresses
          Value:
          - Ref: ADDnsIpAddresses1
          - Ref: ADDnsIpAddresses2
      BlockDeviceMappings:
        -
          DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 
              Ref: VolumeSize
            VolumeType: gp2    
      KeyName:
        Ref: KeyPair
      ImageId:
        Ref: AMI
      InstanceType:
        Ref: InstanceType
      Tags:
      - Key: Name
        Value: myEC2Instance
      SubnetId:
        Ref: PublicSubnet
  myInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
       - EC2DomainJoin 
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value:
      Ref: myEC2InstanceSSM
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - myEC2InstanceSSM
      - AvailabilityZone
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - myEC2InstanceSSM
      - PublicDnsName
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - myEC2InstanceSSM
      - PublicIp        