AWSTemplateFormatVersion: 2010-09-09
Description: ElasticsearchDomain resource
Parameters:
  EnvironmentName:
    Type: String
    Description: Name of the current Environment.
  DomainName:
    Description: User defined Elasticsearch Domain name
    Type: String
  ElasticsearchVersion:
    Description: User defined Elasticsearch Version
    Type: String
    Default: 5.5
  InstanceType:
    Type: String
    Default: t2.small.elasticsearch
  Subnet:
    Description: Select Subnet.
    Type: AWS::EC2::Subnet::Id
  vpc:
    Description: Select VPC.
    Type: AWS::EC2::VPC::Id
  SecurityGroup:
    Description: Security Grouproup for EC2.
    Type: String

Resources:
  ElasticsearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: !Ref DomainName
      ElasticsearchVersion: !Ref ElasticsearchVersion
      ElasticsearchClusterConfig:
        InstanceCount: '1'
        InstanceType: !Ref InstanceType
      EBSOptions:
        EBSEnabled: 'true'
        Iops: 0
        VolumeSize: 10
        VolumeType: standard
      SnapshotOptions:
        AutomatedSnapshotStartHour: '0'
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: '*'
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: 'true'
      Tags:
        - Key: user
          Value: test
      VPCOptions:
        SubnetIds: 
          - !Ref Subnet
        SecurityGroupIds: 
          - !Ref SecurityGroup
Outputs:
  DomainArn:
    Value: !GetAtt ElasticsearchDomain.DomainArn
  DomainEndpoint:
    Value: !GetAtt ElasticsearchDomain.DomainEndpoint
  SecurityGroupId:
    Value: !Ref SecurityGroup
  SubnetId:
    Value: !Ref Subnet